### ISSUE TITLE
Clip brushes block some entities they shouldn't

### ISSUE THREAD

**Issue by Joshua-Ashton** [Joshua-Ashton/VPhysics-Jolt#1]
Some clips block entities that they shouldn't. Some player clips can block physics objects sometimes...

**Comment by FOTMarut** [comment]
Can confirm

**Comment by Thespikedballofdoom** [comment]
I've found vjolt_linearcast 0 helped in gmod for this, i'm not sure if it will help all cases though

**Comment by gris-fuego** [comment]
> I've found vjolt_linearcast 0 helped in gmod for this, i'm not sure if it will help all cases though

For some reason I can't set it to 0, it just sets it to some absurdly high number instead.

**Comment by Thespikedballofdoom** [comment]
it has to be set before server load

**Comment by gris-fuego** [comment]
I've added it to server.cfg, or is there somewhere else it needs to be set?

**Comment by Thespikedballofdoom** [comment]
No clue, I just did it in the console before i made my server
