### ISSUE TITLE
System (MDLCACHE004) failed during stage CONNECTION

### ISSUE THREAD

**Issue by eFeTRn** [Joshua-Ashton/VPhysics-Jolt#103]
I get this error message when booting up source sdk 2013 multiplayer.

**Comment by ZeroFighter17** [comment]
Same issue, but with Gmod.

**Comment by cmdrneon** [comment]
Also having this issue on Gmod. Linux, Debian 11, 64-bit branch.

**Comment by cmdrneon** [comment]
Was able to fix my copying all contents of the ZIP file over to `[gmod]/bin/linux64` rather than just `vphysics.so` and `vphysics_client.so`

**Comment by Joshua-Ashton** [comment]
Yes. You do need all the DLLs.
