### ISSUE TITLE
CI should build for SDK 2013 SP

### ISSUE THREAD

**Issue by Joshua-Ashton** [Joshua-Ashton/VPhysics-Jolt#12]
I was under the assumption that nobody really used SDK 2013 SP because it was horrifically broken in many ways, but I have had a few requests for it (and it would also work on the regular SP games like Portal/HL2)

**Comment by TheAwesome98-Real** [comment]
> because it was horrifically broken in many ways

what ways? like the bug of where npcs can't blink but it was fixed on the internal valve hl2 branch?

**Comment by HazardousGen** [comment]
what about source mods? and if it does work with sp games then can you tell how to do it?

**Comment by Joshua-Ashton** [comment]
Yes it will work for mods.

This is implemented now and builds are on the CI.
