### ISSUE TITLE
GMOD gives no indication that Volt is installed.

### ISSUE THREAD

**Issue by W1nKille3r** [Joshua-Ashton/VPhysics-Jolt#121]
The first time I installed a mod. It worked and I tested it. Then when I tried to do it again. The standard Havok was used. I sinned that Reshade interferes with Volt. But after removing it, it didn't work. Tried to switch to the beta test menu with and without chromium

**Comment by Joshua-Ashton** [comment]
It adds vjolt_ convars if it works.
