### ISSUE TITLE
vphysics jolt breaking most of the game

### ISSUE THREAD

**Issue by AtpZombie42** [Joshua-Ashton/VPhysics-Jolt#127]
bones of npcs get manipulated a shit ton, unnecessary physics getting applied to ragdolls making gore mods evaporate them
sound glitches sometimes, feels like a gmod arg

**Comment by NathanX-S** [comment]
This doesn't explain or focus on any one issue in particular.

**Comment by thiccelf83** [comment]
god you people are so stupid

**Comment by AtpZombie42** [comment]
> This doesn't explain or focus on any one issue in particular.

aside from the whole game breaking

**Comment by f0rttnite** [comment]
by the whole game breaking do you mean the game crashes instantly? is it completely unplayable? what are you doing that causes issues?

**Comment by AtpZombie42** [comment]
https://user-images.githubusercontent.com/77166044/191793754-13d71275-3ff2-43ff-88a1-846f8df2dc48.mp4

**Comment by NathanX-S** [comment]
AFAIK incompatibility with gore mods is known. This isn't "whole game breaking" though.

**Comment by AtpZombie42** [comment]
edit: seems to be an issue with mods not getting unmounted properly
since this isn't a vjolt issue this can be closed
