### ISSUE TITLE
vphysics does not load.

### ISSUE THREAD

**Issue by thiccelf83** [Joshua-Ashton/VPhysics-Jolt#129]
Installed this on 32bit gmod - dropped the win32 files into bin, replaced as needed

launch game, throws error that vphysics failed to load.

**Comment by ScottVordem** [comment]
You need 64-bit Garry's Mod, this will not work at all in 32-bit. You can get it in the betas tab through Steam in the game's properties. Select the one that has `x86_64` in the name.

Also, you need to place them in `bin/win64` afterwards.

**Comment by Joshua-Ashton** [comment]
We don't support 32-bit gmod
