### ISSUE TITLE
Volt for Garry's Mod crash (Windows 7 or missing instruction set?)

### ISSUE THREAD

**Issue by Kleadron** [Joshua-Ashton/VPhysics-Jolt#13]
To install volt into my gmod installation, I replaced the vphysics.dll with the vphysics_jolt_static.dll in my garry's mod bin/win64 folder by renaming it to the same filename and replacing the old one.
The window closes with no information, and the game crashes as soon as I try to load into a map, in singleplayer.
I am using the x86_64 branch for garry's mod and started the game in 64-bit.
My friend is able to run it just fine, doing the exact same thing I did. 

Two important points of info; I am using Windows 7, and I have an AMD FX-6100 CPU.
I assume that the problem is the physics library doesn't support Windows 7, or it is compiled to use an instruction set my CPU doesn't have, per [https://github.com/jrouwe/JoltPhysics#required-cpu-features](url)

I am wondering if a solution or seperate build could be provided if it's not too much effort?

**Comment by Slartibarty** [comment]
Hmm, that CPU might be missing one of the new intrinsics we're using, I'll check it out.

Here's the specific feature macros we're using, could be one of these that's missing:
`SSE4.1 SSE4.2 LZCNT TZCNT F16C FMADD`

**Comment by JillCrungus** [comment]
Chipping in to say that it's running fine for me on Windows 7 on an Intel i5-3470

**Comment by Synkstar** [comment]
Yeah I just tested it on an old xeon x5675 machine running windows 10 but it doesn't load probably from the instructions missing. This cpu was released in the same year as that FX-6100

**Comment by PhoenixStardash** [comment]
Yep, im getting a crash on SDK 2013 MP. 
![image](https://user-images.githubusercontent.com/20983494/187262812-986f75fc-cde3-4589-b526-0f15198fc003.png)

These are my instruction sets. Same year as the Xeon X5675 as well.

**Comment by jrouwe** [comment]
I think you'll have to remove LZCNT, TZCNT, F16C and FMADD for CPU's this old.

**Comment by freedom7341** [comment]
Crashes on my Xeon x5450 w/ Windows 7. Is there a workaround?

**Comment by jrouwe** [comment]
I think this is a matter of editing joltphysics\joltphysics_settings.vpc and changing

'''
		// CPU feature macros, we may want to tune these before release.
		$PreprocessorDefinitions		"$BASE;JPH_USE_SSE4_1;JPH_USE_SSE4_2;JPH_USE_LZCNT;JPH_USE_TZCNT;JPH_USE_F16C;JPH_USE_FMADD"

		$GCC_ExtraCompilerFlags			"$BASE -msse4.1 -msse4.2 -mlzcnt -mf16c -mfma"
'''

to

'''
		// CPU feature macros, we may want to tune these before release.
		$PreprocessorDefinitions		"$BASE;JPH_USE_SSE4_1;JPH_USE_SSE4_2"

		$GCC_ExtraCompilerFlags			"$BASE -msse4.2"
'''

and then recompiling.

**Comment by Joshua-Ashton** [comment]
Yeah. I was thinking of making a stub DLL that checks CPU features and forwards the interface along (SSE2 level, SSE 4.2 level, AVX2 level).
I was wondering if there was a big enough advantage to the other features to warrant the complexity though.

**Comment by Joshua-Ashton** [comment]
https://github.com/Joshua-Ashton/VPhysics-Jolt/issues/46

**Comment by jrouwe** [comment]
I think the stub DLL is a good solution, but costs a lot of time to implement. In a synthetic test the difference between a fully optimized build using AVX2 vs a SSE2 build is about 15%. I haven't tested going from SSE4.2 with LZCNT, TZCNT and F16C to only SSE4.2 (or perhaps even SSE2), but my guess is that it will be much less than 15%. So to make your users happy I would accept the small performance cost for now until you have the time to make a stub.
