### ISSUE TITLE
discord server? (+hard crash error)

### ISSUE THREAD

**Issue by GittyMuh** [Joshua-Ashton/VPhysics-Jolt#137]
anyway. 
when i spawn this dupe : https://steamcommunity.com/sharedfiles/filedetails/?id=113272705

and i shoot and destroy the elevator...
IT HARD CRASHED MY GAME
will this be fixed? when i played a map and a cable was attached to a door. when the door sparked. and im guessing the cable was detached, or destroyed. my game once again froze. and crashed. without any way to reverse it. crashed to desktop.

**Comment by GittyMuh** [comment]
idk what it is. ropes? pulleys?
but when its attached to a breakable prop or something happens with the map where a cable gets detached from a surface. my game crashes to desktop

**Comment by Bagellll** [comment]
#85

**Comment by GittyMuh** [comment]
> #85
> 
> This same dupe led me to investigate and it's because of expanding hydraulics

its not just hydraulics that cause a hard crash. its any map based event where a rope entity falls off of a surface/is disconnected.

**Comment by GittyMuh** [comment]
like when a cable sparks and breaks off a surface
