### ISSUE TITLE
SSE2 and SSE4.2 builds use AVX2 instructions

### ISSUE THREAD

**Issue by AndrewBetson** [Joshua-Ashton/VPhysics-Jolt#138]
While trying to help an acquaintance get VJolt working on their TF2 server (which is hosted on a machine using an `Intel Xeon E5-2690 v2`, which doesn't support AVX2) I noticed that the binaries output by the SSE2 and SSE4.2 projects use AVX2 instructions, as shown by [elfx86exts](https://github.com/pkgw/elfx86exts/) in the attachment below.

I believe this is caused by the `joltphysics_avx2.vpc` script setting the `VOLT_AVX2` conditional and not *un*setting it, causing the SSE2 and SSE4.2 projects to also use the AVX2-specific settings defined in `jolyphysics_settings.vpc`
![avx2](https://user-images.githubusercontent.com/7203160/191806070-8d998602-7e91-45bd-b583-67b63fa74eb6.png)

**Comment by Xeogin** [comment]
It doesn't seem like any of the forks have fixed this in their releases or "action builds" yet. Is this something easy to do for a novice or can someone explain the basics?
