### ISSUE TITLE
Vehicles collisions problems

### ISSUE THREAD

**Issue by hugoheml** [Joshua-Ashton/VPhysics-Jolt#145]
Hi,
When you spawned a vehicle, the vehicle will do some bugged movements as you can see in the video below :
https://youtu.be/4n1-o6pqevg

Also, if you want to drive some vehicles, it's doesn't work at all.

**Comment by NathanX-S** [comment]
Known issue, multiple duplicates exist.

**Comment by Joshua-Ashton** [comment]
Should be fixed now, feel free to re-open if it isn't.
