### ISSUE TITLE
Ragdoll have no bones

### ISSUE THREAD

**Issue by PIXELMANSES** [Joshua-Ashton/VPhysics-Jolt#146]
![image](https://user-images.githubusercontent.com/115110686/194142789-61f7f1f9-8ca1-46c3-8b5a-5ac588312448.png)
![imagen_2022-10-05_211218976](https://user-images.githubusercontent.com/115110686/194142999-40b5bc01-78a7-4860-b791-5d8441875783.png)
![image](https://user-images.githubusercontent.com/115110686/194143123-feaf5bc4-1f40-4324-a5e3-e22f69e834b8.png)

The legs and arms literally fold and the ragdolls feel like liquid
No, I don't havy any gore mods. Just GalaxyHighMarshal & Zippy blood.
The ragdoll mods I have are: Clamp-A-Force https://steamcommunity.com/sharedfiles/filedetails/?id=2805060634
Realism Ragdoll: https://steamcommunity.com/sharedfiles/filedetails/?id=2527521580
Next gen ragdolls: https://steamcommunity.com/sharedfiles/filedetails/?id=2652046255
Heavier ragdolls: https://steamcommunity.com/sharedfiles/filedetails/?id=2821640676
And Fedhoria: https://steamcommunity.com/sharedfiles/filedetails/?id=2401084957

**Comment by NathanX-S** [comment]
Multiple duplicates exist and this issue also fails to narrow the issue down to a single add-on, rather leaving the burden on maintainers with a plethora of add-ons listed.

**Comment by NathanX-S** [comment]
#134 #96

**Comment by PIXELMANSES** [comment]
Thanks you, it worked
