### ISSUE TITLE
[GMOD] imprecise collisions on small, complex features

### ISSUE THREAD

**Issue by hl2jeep** [Joshua-Ashton/VPhysics-Jolt#150]
collision with small features that have complex geometry (such as gears) have inacurate and/or broken collsion. the video attached demonstrates gears passing through eachother and not meshing as they're supposed to

https://user-images.githubusercontent.com/51200953/199337117-52b308d2-cab0-4c93-9a16-79b5e3d0a1a6.mp4

**Comment by Joshua-Ashton** [comment]
Is it better with higher integration steps via the convar?

**Comment by hl2jeep** [comment]
> Is it better with higher integration steps via the convar?
sorry i don't know what convar that is, where can i find it?

**Comment by Bagellll** [comment]
> sorry i don't know what convar that is, where can i find it?

Probably this here
https://github.com/Joshua-Ashton/VPhysics-Jolt/blob/457a95fca54186a73e5f38419060af98307b0d9c/vphysics_jolt/vjolt_environment.cpp#L55
