### ISSUE TITLE
Combine energy pellet not working for AR2

### ISSUE THREAD

**Issue by smallwalle** [Joshua-Ashton/VPhysics-Jolt#151]
The combine energy pellet being fired from the ar2 has quite a few bugs with it. As seen in this video, you can see all the different behaviors the energy pellet has when being fired. It only works with the player.

https://user-images.githubusercontent.com/83623370/199642530-1c8e1bcc-049d-4997-bd63-84b514c135c1.mov

**Comment by Adrianilloo** [comment]
You tried to show a bug where shooting the ball over a platform aiming below it causes it to initially collide and ricochet on the platform, right? I've recently found the bug as well, using [a7fece4](https://github.com/Joshua-Ashton/VPhysics-Jolt/actions/runs/4556477136/jobs/8036878195)

**Comment by Adrianilloo** [comment]
@Joshua-Ashton  As a workaround, I've found setting `vjolt_substeps_integration` higher than `1` seems to fix it, but then it requires to match `vjolt_substeps_collision` value with the former to prevent other issues (such as auto-returned elevators getting stopped, on a certain HL2DM map), so this config should fix it, for instance (where I prefer to use max. values):

```
vjolt_substeps_collision 4 // Match with below change to prevent other issues
vjolt_substeps_integration 4 // Fix incorrect AR2 balls ricochet from platforms
```

**Comment by Joshua-Ashton** [comment]
This seems to be fixed with the implicit velocity fixes.

Let me know if you are still having issues.
