### ISSUE TITLE
ragdolls are just pretty bad and spines of ragdolls are too flexible

### ISSUE THREAD

**Issue by horizon1g** [Joshua-Ashton/VPhysics-Jolt#153]
just what it says in the title and sometimes the knees bend the wrong way etc

**Comment by caoqt1** [comment]
pretty sure thats what you get when you combine a new physics engine and old ass ragdolls that weren't made for new physics engine

**Comment by imadeagithubaccountforthis** [comment]
yeah, this is likely unfixable without some weird addon that somehow fixes the ragdolls, but they are funny so... (proof attached)
![20240421202134_1](https://github.com/Joshua-Ashton/VPhysics-Jolt/assets/81992759/57331f7d-864c-4c75-963e-1bb4ddbdb06c)

**Comment by Joshua-Ashton** [comment]
Fixed.
