### ISSUE TITLE
Touching props when noclipping bug

### ISSUE THREAD

**Issue by severijj** [Joshua-Ashton/VPhysics-Jolt#164]
When I noclip through a prop, the physics engine registers it as me touching the prop, moving it

I am using the x86-64 version of Garry's Mod on linux, and have no addons enabled

https://user-images.githubusercontent.com/122631629/212382141-ed318c82-3700-40b3-a605-9c3d7af60a53.mp4

**Comment by JokerR3310** [comment]
actually it https://github.com/Joshua-Ashton/VPhysics-Jolt/issues/18

**Comment by Joshua-Ashton** [comment]
Fixed.
