### ISSUE TITLE
How do i uninstall this?

### ISSUE THREAD

**Issue by tpopbpmg** [Joshua-Ashton/VPhysics-Jolt#165]
Hi, i enjoyed this mod but the vehicle physics make it a bit bad for me. Can i uninstall this somehow? (no offense)

**Comment by Xcalibur10** [comment]
Easiest way is to validate your installation files in Steam so it'll redownload the original physics file. The reason why it's bad, because that part is incomplete yet. Sadly, not everything supported. I hope the project isn't abandoned.
