### ISSUE TITLE
Constraint crashes on Linux

### ISSUE THREAD

**Issue by Joshua-Ashton** [Joshua-Ashton/VPhysics-Jolt#17]
Had some reports of constraints crashing under Linux.

A simple repro is apparently to create and undo a rope in a Garry's Mod server under Linux.

Probably need to run under valgrind or something, because it looks like a heap corruption/double-free error based on the spew.

Didn't catch this because the GMod Native Linux Client doesn't work anymore *sigh* and I only briefly smoke-tested the server. :frog: I asked around, and apparently this can workaround the native client not working at all: [https://github.com/solsticegamestudios/GModCEFCodecFix](https://github.com/solsticegamestudios/GModCEFCodecFix/releases/tag/20220528), but I haven't had a chance to test yet.

**Comment by klen-list** [comment]
I noticed that an undo crash occurs with rope that attached to world at one of its own ends and after spawning props with different models. In cases of similar model or prop-to-prop rope crash doesn't happen.

Steps to reproduce:
1. Spawn `models/props_borealis/bluebarrel001.mdl`
2. Attach rope from barrel to world
3. Spawn `models/props_c17/FurnitureWashingmachine001a.mdl`
4. Press undo button twice (or open SpawnMenu->Utilities->User->Undo and click at `Rope`)

https://user-images.githubusercontent.com/49125075/188244870-239b309d-439e-4f17-9fe1-9b2155ef69eb.mp4

I also get the same crash with `free(): corrupted unsorted chunks` when undo a large count of identical wheels welded to world.
