### ISSUE TITLE
Missing createjoltprojects scripts

### ISSUE THREAD

**Issue by Adrianilloo** [Joshua-Ashton/VPhysics-Jolt#174]
I wanted to build VPhysics Jolt and can't find `createjoltprojects.bat` / `createjoltprojects.sh` scripts, yet they are referenced in the Actions workflow.

Where are these?

**Comment by Joshua-Ashton** [comment]
See https://github.com/Joshua-Ashton/VPhysics-Jolt/blob/main/build.md

These scripts are in eg. https://github.com/Joshua-Ashton/mini-source-sdk/tree/master/sdk2013-sp/src

**Comment by Adrianilloo** [comment]
Thank you. I didn't properly read the initial steps and assumed I could use my SSDK2013 project.
