### ISSUE TITLE
Development builds are not being updated on froggi.es

### ISSUE THREAD

**Issue by SweptWasTaken** [Joshua-Ashton/VPhysics-Jolt#181]
As outlined in the readme:

> Development builds for each commit for Garry's Mod are available on [froggi.es](https://git.froggi.es/joshua/vphysics_jolt_gmod_builds).

When going to the link however, the build is only updated to commit https://github.com/Joshua-Ashton/VPhysics-Jolt/commit/067cc7eb4e5a145f4c3be6629f597809a5ca1317.

**Comment by Joshua-Ashton** [comment]
This is fixed now.

**Comment by WinterPhoenix** [comment]
This is an issue again
