### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by SanyaSho** [Joshua-Ashton/VPhysics-Jolt#182]
![изображение](https://github.com/Joshua-Ashton/VPhysics-Jolt/assets/68691958/a09842cf-a07e-4e85-af62-db9dbc0f3b04)

**Comment by YUCLing** [comment]
What's your CPU?

**Comment by SanyaSho** [comment]
Intel(R) Core(TM) i7 CPU 860 @ 2.80GHz
