### ISSUE TITLE
Compatibility with 2013 SP branch?

### ISSUE THREAD

**Issue by davie504** [Joshua-Ashton/VPhysics-Jolt#19]
![image](https://user-images.githubusercontent.com/59658354/187143862-bf4d15ca-fd23-45b9-a0c9-7ae190ce5610.png)

**Comment by Joshua-Ashton** [comment]
Duplicate of: https://github.com/Joshua-Ashton/VPhysics-Jolt/issues/12

**Comment by Joshua-Ashton** [comment]
SDK 2013 SP builds are on the CI now.
