### ISSUE TITLE
KeyValues Error: RecursiveLoadFromBuffer:  got } in key in file VPhysicsKeyParse (or my skill issue)

### ISSUE THREAD

**Issue by bydlocodd** [Joshua-Ashton/VPhysics-Jolt#20]
installed `vphysics_jolt_sdk2013_win32` on Windows SRCDS and started the server on rp_bangclaw, after which the following messages appeared:

![image](https://user-images.githubusercontent.com/62701792/187196838-47db3fc7-4735-4d88-8853-5700f03dbd91.png)

The info_ladder messages were always there. There is speculation that Jolt's messages are related to these. Or i have a skill issue and just installed wrong? Renamed binary to `vphysics.dll` and put it into `bin/`

**Comment by Joshua-Ashton** [comment]
This is because the models have invalid KeyValues data.

Does the kv-wiggleroom branch fix it? You can get the artifacts from GitHub.
