### ISSUE TITLE
No Collide constraint / COLLISION_GROUP_WORLD doesn't work well

### ISSUE THREAD

**Issue by meetric1** [Joshua-Ashton/VPhysics-Jolt#28]
pretty self explanatory, to replicate (in gmod) use the no collide tool and allow the two objects to collide (specifically using physgun with a lot of force)

(or set both props to COLLISION_GROUP_WORLD by disabling collisions using c menu)

**Comment by klen-list** [comment]
looks like objects are still interacting with each other when falling through

https://user-images.githubusercontent.com/49125075/188122389-016791da-f6e0-44b5-8970-36693b28802a.mp4
