### ISSUE TITLE
Server crash on map clean up

### ISSUE THREAD

**Issue by Marshall-vak** [Joshua-Ashton/VPhysics-Jolt#29]
When a map cleanup is called from `game.CleanUpMap()` the server states the following error `free(): corrupted unsorted chunks` and hangs. 

The server is srcds x64 on Linux. Distro: ubuntu

**Comment by Joshua-Ashton** [comment]
Duplicate of: https://github.com/Joshua-Ashton/VPhysics-Jolt/issues/17
