### ISSUE TITLE
AppFramework : Unable to load module vphysics.dll!

### ISSUE THREAD

**Issue by sonicobsessinter** [Joshua-Ashton/VPhysics-Jolt#33]
So I may be an idiot, but I downloaded the Windows 64bit file and went to the file directory for Garrys Mod and replaced the vphysics.dll with the file from the download, and specifically, in the directions, it says "Note that you must rename the DLL, simply placing it in the directory will not work." which I am assuming it means the file cannot be used if the file has the name that it came within the downloads, it has to be changed to what Garry's Mod has typically as the physics file "vphysics.dll"

Originally I had renamed the file while the file was within the directory folder, and windows and or programs can be wonky sometimes, so I decided to delete the file and rename the file in another folder to the correct name and replace it after that.

So I ended up getting this error 
![image](https://user-images.githubusercontent.com/74119250/187320477-687cde99-2f34-4fa6-a5b1-82a449e1583f.png)

I did what the instructions dictated as I understood them, if this is a simple fix let me know. Also if there is any way I can get crash logs, I would absolutely provide them it just doesn't seem like there is a way to get them.

**Comment by zt64** [comment]
Maybe the dll in the release should be named as `vphsyics.dll` so it'll just prompt the user to replace when putting it in the win64 dir? That would simplify it I think. I was also confused with this

**Comment by sonicobsessinter** [comment]
> You need to make sure you use x86_64 gmod and put it in bin/win64

This fixed it I literally just realized what I did wrong. Enable this in Properties on steam in Beta.

**Comment by johndonn297** [comment]
i have this issue still. i use the x86_64 version.

**Comment by sonicobsessinter** [comment]
> i have this issue still. i use the x86_64 version.

Did you rename the file in the Gmod folder?

**Comment by johndonn297** [comment]
> > i have this issue still. i use the x86_64 version.
> 
> Did you rename the file in the Gmod folder?

Yes. When I name it vphysics.dll it just gives me this error. I have the right version. I have no mods. I don't have any misspellings. Everything is normal.
