### ISSUE TITLE
Null pointer dereference in JoltPhysicsCollision::CollideGetAABB

### ISSUE THREAD

**Issue by khang06** [Joshua-Ashton/VPhysics-Jolt#35]
I get a crash when I load [gm_fork](https://steamcommunity.com/sharedfiles/filedetails/?id=326332456) on GMod.
![image](https://user-images.githubusercontent.com/11239786/187335089-86cb13be-c03c-4c37-93e3-24283b4807a9.png)

Looks like the crash is on [this line.](https://github.com/Joshua-Ashton/VPhysics-Jolt/blob/11adbb57bd35716bc7731ee6550e15bdddb8dd13/vphysics_jolt/vjolt_collide.cpp#L283)

Right before the crash, this gets logged:
`Skipped solid 0 due to invalid header (id: 0\x1A\x89?, version: 0xffff80ee)`

**Comment by Joshua-Ashton** [comment]
Yeah that log line would be the root cause of the problem... Do you know if it's part of the map or a model that's the problem?

**Comment by khang06** [comment]
Looks like it's caused by a file called `bridge_railing.phy`, which isn't included with the map. Not sure where it is right now, but I'll try looking.

**Comment by khang06** [comment]
Okay, I found it. Not sure if you're okay with me uploading the model here, but you can find it in Half Life 2's `hl2_misc_dir.vpk` in `models/props_wasteland`.

**Comment by Joshua-Ashton** [comment]
Fixed by that commit, will be in the next release
