### ISSUE TITLE
Question about JoltPhysics

### ISSUE THREAD

**Issue by AndreaCatania** [Joshua-Ashton/VPhysics-Jolt#39]
Hello,

This is not an issue, but a question. I hope it's ok if I ask here.

I saw this project name is `VPhysics-Jolt` and I wonder if this has something to do with https://github.com/jrouwe/JoltPhysics that essentially has the same name.
Is it just a coincidence or do you plan to merge these two projects?

**Comment by davie504** [comment]
Vphysics is just an interface. Jolt is an physics engine.

**Comment by Joshua-Ashton** [comment]
VPhysics-Jolt is an implementation of VPhysics using Jolt Physics. For any future questions, it may be better to use the `Discussions` feature.

**Comment by AndreaCatania** [comment]
It makes a lot of sense now, thanks!

However, `Discussions` is not visible for me:
![Screenshot from 2022-08-30 09-24-38](https://user-images.githubusercontent.com/8342599/187375783-02b11967-a253-4a3f-bfc7-c7c93891ad63.png)

**Comment by Joshua-Ashton** [comment]
Try now?

**Comment by AndreaCatania** [comment]
Boom fixed!
