### ISSUE TITLE
The game does not start with an error

### ISSUE THREAD

**Issue by swinglynn01** [Joshua-Ashton/VPhysics-Jolt#40]
The game does not start after replacing the default vphysics.dll with vjolt.
Error: AppFramework : Unable to load module vphysics.dll.

I did everything according to the instructions, first I downloaded the archive, updated the game to a 64-bit branch, unpacked it according to the specified path, deleted the standard vphysics.dll, and renamed vjolt to vphysics.dll

**Comment by Tr3yWay996** [comment]
yes me too idk why
it just crash without anything

**Comment by swinglynn01** [comment]
![52FE1703-A109-4321-98D2-FDB2707F7886](https://user-images.githubusercontent.com/112482897/187466671-95013686-aa88-4b6c-a9f3-bebd7b9083da.jpeg)

**Comment by johndonn297** [comment]
same issue

**Comment by Joshua-Ashton** [comment]
https://github.com/Joshua-Ashton/VPhysics-Jolt/issues/46
