### ISSUE TITLE
G-Mod Crashing When Trying To Start  Session

### ISSUE THREAD

**Issue by An-Unknown-Player** [Joshua-Ashton/VPhysics-Jolt#41]
I did everything as told, replace the old file with the new one, renamed the `vphysics_jolt_static.dll` file to `vphysics.dll`, checked that it installed correctly by typing `vjolt_` into the console, but when starting a session it crashes almost instantly.

Here's the crash report:
```
Executable: G:\SteamLibrary_Gmod\steamapps\common\GarrysMod\bin\win64\gmod.exe

-Lua Stack Traces-
==================
  Client
    Lua Interface = NULL

  Server
    Lua Interface = NULL

  MenuSystem
    *Not in Lua call OR Lua has panicked*

-Console Buffer-
================
46(98.809324):  PREP OK
45(98.761161):  Network: IP 192.168.1.192, mode MP, dedicated No, ports 27015 SV / 27005 CL
44(98.740886):  DEBUG: Clearing CSoundPatches after soundsound...
43(98.740854):  DEBUG: Clearing CSoundPatches after soundsound...
42(98.738408):  DEBUG: Clearing CSoundPatches after soundsound...
41(98.738370):  DEBUG: Clearing CSoundPatches after soundsound...
40(98.530360):  DEBUG: Clearing CSoundPatches after soundsound...
39(98.530327):  DEBUG: Clearing CSoundPatches after soundsound...
38(50.909725):  asset://garrysmod/html/menu.html#/newgame/:0: Autofocus processing was blocked because a document's URL has a fragment '#/newgame/'.
37(50.909711):  36(50.909697):  [HTML] 35(50.909664):  34(32.098952):  Addons have changes - remounting
33(32.079986):  Mounting Floating Addon 'addons\spatzer_tf2_addons_reactivasion\team_fortress_2_customizable_mercenaries_1573115908.gma'
32(32.078779):  Mounting Floating Addon 'addons\spatzer_tf2_addons_reactivasion\paintable_team_fortress_2_mercenaries_432633045.gma'
31(32.077571):  Mounting Floating Addon 'addons\spatzer_tf2_addons_reactivasion\colourable_tf2_intel_280655383.gma'
30(32.076310):  Mounting Floating Addon 'addons\spatzer_tf2_addons_reactivasion\colourable_tf2_gameplay_props_298075685.gma'
29(32.074996):  Mounting Floating Addon 'addons\spatzer_tf2_addons_reactivasion\colourable_tf2_buildables_316236860.gma'
28(31.721913):  '[ArcCW] Cheaty attachments' is missing Addon, ServerContent, Dupe, Demo or Save tag!
27(31.695779):  'M9K Specialties' is missing Addon, ServerContent, Dupe, Demo or Save tag!
26(31.300436):  '[ASP] Custom Mark VII Playermodel' is missing Addon, ServerContent, Dupe, Demo or Save tag!
25(31.281804):  '[UMP] Halo 2 Anniversary Marine' is missing Addon, ServerContent, Dupe, Demo or Save tag!
24(31.280378):  '[DRC] Halo Rebirth' is missing Addon, ServerContent, Dupe, Demo or Save tag!
23(31.219343):  'Medkit & Suit Battery Remake' is missing Addon, ServerContent, Dupe, Demo or Save tag!
22(19.174227):  DEBUG: Clearing CSoundPatches after soundsound...
21(19.174191):  DEBUG: Clearing CSoundPatches after soundsound...
20(18.983637):  Not playing a local game.
19(18.983548):  Advanced Joystick settings initialized
18(18.983545):  JOY_AXIS_V:  unmapped
17(18.983541):  JOY_AXIS_U:  mapped to Side (absolute)
16(18.983537):  JOY_AXIS_R:  mapped to Forward (absolute)
15(18.983533):  JOY_AXIS_Z:  unmapped
14(18.983529):  JOY_AXIS_Y:  mapped to Look (absolute)
13(18.983513):  JOY_AXIS_X:  mapped to Turn (absolute)
12(14.084696):  Parent cvar in server.dll not allowed (p2p_enabled)
11(12.134684):  x86-64: gmod_mcore_test=1
10(3.749955):  Adding Filesystem Addon 'g:\steamlibrary_gmod\steamapps\common\garrysmod\garrysmod\addons\warriorspear'
9(3.748999):  Adding Filesystem Addon 'g:\steamlibrary_gmod\steamapps\common\garrysmod\garrysmod\addons\v-tools'
8(3.747901):  Adding Filesystem Addon 'g:\steamlibrary_gmod\steamapps\common\garrysmod\garrysmod\addons\temp'
7(3.746917):  Adding Filesystem Addon 'g:\steamlibrary_gmod\steamapps\common\garrysmod\garrysmod\addons\spatzer_tf2_addons_reactivasion'
6(3.745987):  Adding Filesystem Addon 'g:\steamlibrary_gmod\steamapps\common\garrysmod\garrysmod\addons\soft_lamps_[updated_july_2018]_636153716'
5(3.744516):  Adding Filesystem Addon 'g:\steamlibrary_gmod\steamapps\common\garrysmod\garrysmod\addons\fu---d_up_splatoon_models'
4(3.743195):  Adding Filesystem Addon 'g:\steamlibrary_gmod\steamapps\common\garrysmod\garrysmod\addons\combine-units-plus-'
3(3.742254):  Adding Filesystem Addon 'g:\steamlibrary_gmod\steamapps\common\garrysmod\garrysmod\addons\ck_props_all'
2(3.741087):  Adding Filesystem Addon 'g:\steamlibrary_gmod\steamapps\common\garrysmod\garrysmod\addons\2017_vito_finnish_police_skin'
1(3.450153):  Attempting to load Chromium...
```
What could be causing this crash? I've seen that this is a problem for a lot of people, but none of them have been answered.

**Comment by HazardousGen** [comment]
You Must Disable or Uninstall All of your Addons

**Comment by tqoac** [comment]
> You Must Disable or Uninstall All of your Addons

This does not fix the issue, same exact thing is happening to me and I already have zero addons installed.

**Comment by HazardousGen** [comment]
The Log says you do, Check your addons folder and remove them or more them to a other folder.

**Comment by An-Unknown-Player** [comment]
Ok, so I did that, but it didn't work. Here's the updated crash log:
```
Executable: G:\SteamLibrary_Gmod\steamapps\common\GarrysMod\bin\win64\gmod.exe

-Lua Stack Traces-
==================
  Client
    Lua Interface = NULL

  Server
    Lua Interface = NULL

  MenuSystem
    *Not in Lua call OR Lua has panicked*

-Console Buffer-
================
31(54.878406):  PREP OK
30(54.855943):  DEBUG: Clearing CSoundPatches after soundsound...
29(54.855906):  DEBUG: Clearing CSoundPatches after soundsound...
28(54.853452):  DEBUG: Clearing CSoundPatches after soundsound...
27(54.853414):  DEBUG: Clearing CSoundPatches after soundsound...
26(54.645258):  DEBUG: Clearing CSoundPatches after soundsound...
25(54.645224):  DEBUG: Clearing CSoundPatches after soundsound...
24(52.405229):  asset://garrysmod/html/menu.html#/newgame/:0: Autofocus processing was blocked because a document's URL has a fragment '#/newgame/'.
23(52.405206):  22(52.405187):  [HTML] 21(52.405146):  20(33.764055):  Addons have changes - remounting
19(33.396570):  '[ArcCW] Cheaty attachments' is missing Addon, ServerContent, Dupe, Demo or Save tag!
18(33.372558):  'M9K Specialties' is missing Addon, ServerContent, Dupe, Demo or Save tag!
17(32.986927):  '[ASP] Custom Mark VII Playermodel' is missing Addon, ServerContent, Dupe, Demo or Save tag!
16(32.969395):  '[UMP] Halo 2 Anniversary Marine' is missing Addon, ServerContent, Dupe, Demo or Save tag!
15(32.968084):  '[DRC] Halo Rebirth' is missing Addon, ServerContent, Dupe, Demo or Save tag!
14(32.908606):  'Medkit & Suit Battery Remake' is missing Addon, ServerContent, Dupe, Demo or Save tag!
13(17.703159):  DEBUG: Clearing CSoundPatches after soundsound...
12(17.703125):  DEBUG: Clearing CSoundPatches after soundsound...
11(17.517221):  Not playing a local game.
10(17.517130):  Advanced Joystick settings initialized
9(17.517127):  JOY_AXIS_V:  unmapped
8(17.517123):  JOY_AXIS_U:  mapped to Side (absolute)
7(17.517119):  JOY_AXIS_R:  mapped to Forward (absolute)
6(17.517116):  JOY_AXIS_Z:  unmapped
5(17.517112):  JOY_AXIS_Y:  mapped to Look (absolute)
4(17.517093):  JOY_AXIS_X:  mapped to Turn (absolute)
3(13.289179):  Parent cvar in server.dll not allowed (p2p_enabled)
2(11.364134):  x86-64: gmod_mcore_test=1
1(3.427462):  Attempting to load Chromium...
```

**Comment by HazardousGen** [comment]
> > You Must Disable or Uninstall All of your Addons
> 
> This does not fix the issue, same exact thing is happening to me and I already have zero addons installed.

Check your Addons Folder 
C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\addons

**Comment by HazardousGen** [comment]
> Ok, so I did that, but it didn't work. Here's the updated crash log:
> 
> ```
> Executable: G:\SteamLibrary_Gmod\steamapps\common\GarrysMod\bin\win64\gmod.exe
> 
> -Lua Stack Traces-
> ==================
>   Client
>     Lua Interface = NULL
> 
>   Server
>     Lua Interface = NULL
> 
>   MenuSystem
>     *Not in Lua call OR Lua has panicked*
> 
> -Console Buffer-
> ================
> 31(54.878406):  PREP OK
> 30(54.855943):  DEBUG: Clearing CSoundPatches after soundsound...
> 29(54.855906):  DEBUG: Clearing CSoundPatches after soundsound...
> 28(54.853452):  DEBUG: Clearing CSoundPatches after soundsound...
> 27(54.853414):  DEBUG: Clearing CSoundPatches after soundsound...
> 26(54.645258):  DEBUG: Clearing CSoundPatches after soundsound...
> 25(54.645224):  DEBUG: Clearing CSoundPatches after soundsound...
> 24(52.405229):  asset://garrysmod/html/menu.html#/newgame/:0: Autofocus processing was blocked because a document's URL has a fragment '#/newgame/'.
> 23(52.405206):  22(52.405187):  [HTML] 21(52.405146):  20(33.764055):  Addons have changes - remounting
> 19(33.396570):  '[ArcCW] Cheaty attachments' is missing Addon, ServerContent, Dupe, Demo or Save tag!
> 18(33.372558):  'M9K Specialties' is missing Addon, ServerContent, Dupe, Demo or Save tag!
> 17(32.986927):  '[ASP] Custom Mark VII Playermodel' is missing Addon, ServerContent, Dupe, Demo or Save tag!
> 16(32.969395):  '[UMP] Halo 2 Anniversary Marine' is missing Addon, ServerContent, Dupe, Demo or Save tag!
> 15(32.968084):  '[DRC] Halo Rebirth' is missing Addon, ServerContent, Dupe, Demo or Save tag!
> 14(32.908606):  'Medkit & Suit Battery Remake' is missing Addon, ServerContent, Dupe, Demo or Save tag!
> 13(17.703159):  DEBUG: Clearing CSoundPatches after soundsound...
> 12(17.703125):  DEBUG: Clearing CSoundPatches after soundsound...
> 11(17.517221):  Not playing a local game.
> 10(17.517130):  Advanced Joystick settings initialized
> 9(17.517127):  JOY_AXIS_V:  unmapped
> 8(17.517123):  JOY_AXIS_U:  mapped to Side (absolute)
> 7(17.517119):  JOY_AXIS_R:  mapped to Forward (absolute)
> 6(17.517116):  JOY_AXIS_Z:  unmapped
> 5(17.517112):  JOY_AXIS_Y:  mapped to Look (absolute)
> 4(17.517093):  JOY_AXIS_X:  mapped to Turn (absolute)
> 3(13.289179):  Parent cvar in server.dll not allowed (p2p_enabled)
> 2(11.364134):  x86-64: gmod_mcore_test=1
> 1(3.427462):  Attempting to load Chromium...
> ```

Still seems to be some addons Check Addons Folder

**Comment by tqoac** [comment]
> > > You Must Disable or Uninstall All of your Addons
> > 
> > 
> > This does not fix the issue, same exact thing is happening to me and I already have zero addons installed.
> 
> Check your Addons Folder C:\Program Files (x86)\Steam\steamapps\common\GarrysMod\garrysmod\addons

I have. I already unsubscribed to all the addons on steam and I cleared my addons folder, the crash is still persisting.

**Comment by HazardousGen** [comment]
Also Did you Switch To x86-64 - Chromium + 64-bit binaries in the Beta properties in Steam?

**Comment by tqoac** [comment]
> Also Did you Switch To x86-64 - Chromium + 64-bit binaries in the Beta properties in Steam?

I have, yes.

**Comment by HazardousGen** [comment]
Did you place vphysics_jolt_static.pdb In Win64, If yes remove it

**Comment by HazardousGen** [comment]
Cant Think of anything, Probably Have to wait until Vjolt Gets better updates

**Comment by An-Unknown-Player** [comment]
Ok, thanks for the help anyway.

**Comment by IntellectualPotato** [comment]
Hmm. have you tried a different map?  alot of maps crash because of a model issue

**Comment by An-Unknown-Player** [comment]
I tired to load default gm_construct.

**Comment by DumdumMan** [comment]
I have the same issue, crashes when loading a map, no addons, fresh install.

**Comment by Chaxlotl** [comment]
why are people mentioning addons its crashing when its attempting to load chromium not the addons

**Comment by Synkstar** [comment]
Its likely because your cpu doesn't support the required instructions that this is compiled with. Currently only really guaranteed to work on newer cpus. I tried older xeons but it doesn't run on those yet this is a known issue. Just crashes right after prep ok for me too on those cpus because thats when it tries to load it up #13

**Comment by Joshua-Ashton** [comment]
https://github.com/Joshua-Ashton/VPhysics-Jolt/issues/46
