### ISSUE TITLE
GetMesh returns inverted triangles

### ISSUE THREAD

**Issue by Mee12345** [Joshua-Ashton/VPhysics-Jolt#44]
![image](https://user-images.githubusercontent.com/73554599/187572047-7100c12e-3c38-4e9c-b52a-75a2ccb08c9c.png)
Picture of a basic sent with a imesh object generated with physobj:GetMesh^

(This is not really a high priority fix, but is something I noticed and may cause problems with some gmod addons)

**Comment by Joshua-Ashton** [comment]
Thanks! Do you have an add-on or lua_run or whatever that can reproduce?

**Comment by Mee12345** [comment]
sure, unzip the attached file & throw it in the addons folder (*/common/GarrysMod/garrysmod/addons)
feel free to mess with the code

[invert_tris.zip](https://github.com/Joshua-Ashton/VPhysics-Jolt/files/9466500/invert_tris.zip)
