### ISSUE TITLE
Base Vehicle HL2 Not working Correctly in Garry's Mod

### ISSUE THREAD

**Issue by HazardousGen** [Joshua-Ashton/VPhysics-Jolt#56]
Jeep And Airboat Not working properly, Like Turbo does not make the vehicle go any faster or airboat does not float in water.

**Comment by Joshua-Ashton** [comment]
Jeep turbo works completely fine here.

Airboat is known to not work as-per feature grid on README.

**Comment by Joshua-Ashton** [comment]
Duplicate of https://github.com/Joshua-Ashton/VPhysics-Jolt/issues/4
