### ISSUE TITLE
Walking up on vphysics stairs is inconsistent

### ISSUE THREAD

**Issue by xen-000** [Joshua-Ashton/VPhysics-Jolt#72]
Stairs that use vphysics collisions (brush entities or props) are inconsistent compared to IVP.

In the following videos, the translucent stairs are func_brushes with `solidbsp 0` and the opaque ones are func_detail.

[Volt](https://www.youtube.com/watch?v=BP5pdJFdkms)
[IVP](https://www.youtube.com/watch?v=y6REQivOfyE)

**Comment by Joshua-Ashton** [comment]
Can you provide the map?

**Comment by xen-000** [comment]
Sure! Here you go:

[stairstest.zip](https://github.com/Joshua-Ashton/VPhysics-Jolt/files/9480209/stairstest.zip)

**Comment by ScottVordem** [comment]
Found a (hopefully) temporary workaround, but it might lag more...at least in Garry's Mod.

Increase `vjolt_player_collision_tolerance` until you can walk up them normally consistently.

**Comment by xen-000** [comment]
Increasing `vjolt_player_collision_tolerance` had no effect when it comes to stairs, at least in both CS:S and Momentum.

**Comment by ScottVordem** [comment]
In Garry's Mod, I have to increase it to a very high value of 1000. I am unable to test Vjolt anywhere else unfortunately.

**Comment by Joshua-Ashton** [comment]
Should be improved now?
