### ISSUE TITLE
simfphys vehicles crash entire Linux machine when deleted

### ISSUE THREAD

**Issue by BBQGiraffe** [Joshua-Ashton/VPhysics-Jolt#78]
I spawned a simfphys vehicle to test out #75 and after confirming the error was present I pressed z and my entire computer promptly crashed and I had to hard reset it, here's the game's crash dump if it helps
[crashdump.zip](https://github.com/Joshua-Ashton/VPhysics-Jolt/files/9481476/crashdump.zip)

**Comment by Synkstar** [comment]
This is just #17 the linux version is just rather buggy interms of crashing atm.
