### ISSUE TITLE
Does not work in gmod

### ISSUE THREAD

**Issue by slavaegg** [Joshua-Ashton/VPhysics-Jolt#81]
My system is a b550 amd MB
A ryzen 7 5700g
Rx6600xt
The physics engine does not change the framerates.

**Comment by slavaegg** [comment]
Also garbage bins now flow down very slowly

**Comment by Joshua-Ashton** [comment]
You probably installed it wrong. It goes in bin/win64 and replaces vphysics.dll.

**Comment by Joshua-Ashton** [comment]
You can tell its loaded by the presence of the vjolt_ cvars

**Comment by Exehad** [comment]
> My system is a b550 amd MB A ryzen 7 5700g Rx6600xt The physics engine does not change the framerates.

Like Joshua said you prob installed it wrong, I run a 64 bit system and I am on the 64 bit gmod version and Jolt works like a dream

**Comment by slavaegg** [comment]
Yep i did , sorry
