### ISSUE TITLE
Hella laggy

### ISSUE THREAD

**Issue by kuwalt2** [Joshua-Ashton/VPhysics-Jolt#91]
im not sure what's going on, is it my specs?
https://youtu.be/jrxVRA9NoaY
no addons enabled

**Comment by Joshua-Ashton** [comment]
You didn't install it correctly.

**Comment by kuwalt2** [comment]
wasn't I supposed to drag and drop the bin?
well then how do I install it?

**Comment by AruMoon** [comment]
> wasn't I supposed to drag and drop the bin? well then how do I install it?

You should use 64 bit gmod beta branch
Go to Garry's Mod/bin/win64 and backup original vphysics.dll and replace it with jolt physics just by moving static lib and rename it to vphysics.dll
