### ISSUE TITLE
Did I install it incorrectly?

### ISSUE THREAD

**Issue by kuwalt2** [Joshua-Ashton/VPhysics-Jolt#92]
It's laggy, and don't work, so I re-installed it. Still laggy. Is this not what it's supposed to look like?
![Screenshot (730)](https://user-images.githubusercontent.com/112900182/188506796-7547c6a1-72c3-40fe-8f9e-aabe5d79f9e8.png)

**Comment by Joshua-Ashton** [comment]
Yes, you rename it to vphysics.dll
