### ISSUE TITLE
[GMOD] 32 bit request

### ISSUE THREAD

**Issue by AruMoon** [Joshua-Ashton/VPhysics-Jolt#94]
Can you add 32 bit garry's mod autobuilds? Some addons for Garry's mod have binary files and they are 32 bit, and that's the reason to still use 32 bit version

**Comment by Bagellll** [comment]
The sdk2013 version actually works pretty well for gmod. I've only tested it with the base branch though.

**Comment by Joshua-Ashton** [comment]
No official support for 32-bit GMod is provided. If X works then that's great, but no official support is provided.
